Helping Hands/Areas/Manager/Controllers/CareVisitController.cs
using Helping_Hands.Data;
using Helping_Hands.Data.GRID;
using Helping_Hands.Data.Repositories;
using Helping_Hands.Models;
using Helping_Hands.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Helping_Hands.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = "Manager")]
    public class CareVisitController : Controller
    {
        private HelpingHandsUnitOfWork data { get; set; }
        private GRP0452HelpingHandsDBContext _context { get; set; }

        private static int CareID;

        public CareVisitController(GRP0452HelpingHandsDBContext ctx)
        {
            data = new HelpingHandsUnitOfWork(ctx);
            _context = ctx;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }


        public IActionResult NurseDetails(int id)
        {
            CareContracts contra = new CareContracts();
            Nurses patie = new Nurses();

        //    contra = data.CareContracts.Get(id);

           // int? ID = contra.NurseUserID;
            patie = data.Nurses.Get(id);

            var pt = new NursesListViewModel
            {


               Nurses = data.Nurses.List(new QueryOptions<Nurses> { 
                
                   Where = a =>a.NurseUserID == id
               
               }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs>
                {
                    Where = b => b.SuburbID == patie.SuburbID
                }),
                Cities = data.Cities.List(new QueryOptions<Cities>
                {
                    Where = c => c.CityID == patie.CityID
                }),

                PreferedSuburbs = data.PreferedSub.List(new QueryOptions<PreferedSuburbs>
                {
                    Where =b=>b.NurseUserID == id

                })

             


            };


      //      var Patient = data.Patients.Get(Convert.ToInt32(ID));


            return View(pt);
        }


        [HttpGet]
        public IActionResult List(CareVisitGridDTO vals)
        {
            string DefaultSort = nameof(CareVisits.VisitDate);
            var builder = new CareVisitGridBuilder(HttpContext.Session, vals, defaultSortField: nameof(CareVisits.VisitDate));
            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());

            var options = new CareVisitQueryOptions
            {

                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection,
                WhereClauses = new WhereClauses<CareVisits>
                {
                    t =>t.NurseUserID == ID
                }

            };




            options.SortFilter(builder);


            var vw = new CareVisitListViewModel
            {

                CareVisit = data.CareVisits.List(options),

                Patients = data.Patients.List(new QueryOptions<Patients>
                {

                    OrderBy = a => a.FirstName
                }),

                Nurses = data.Nurses.List(new QueryOptions<Nurses>
                {
                    OrderBy = b=>b.FirstName

                }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs> { }),
                Cities = data.Cities.List(new QueryOptions<Cities> { }),
                Contracts = data.CareContracts.List(new QueryOptions<CareContracts> { }),

                CurrentRoute = builder.CurrentRoute,


                TotalPages = builder.GetTotalPages(data.CareVisits.Count)


            };

            ////Substrating time and date

            //DateTime date = DateTime.Today;

            //DateTime fort = date.AddDays(-32);
            //ViewBag.Date = fort.ToString("D"); //|| DateTime.Today.ToString("dd");

            return View(vw);


        }

        [HttpPost]
        public IActionResult StartSession(CareVisits visit)
        {
            CareVisits vs = new CareVisits();
            vs = data.CareVisits.Get(visit.CareVisitsID);


            //Start Session
            if (visit.DepartTime == null && visit.WoundCondition == null)
            {

                vs.ArrivalTime = visit.ArrivalTime;

                data.CareVisits.Update(vs);

                data.CareVisits.Save();
            }

            //End Session
            else if (visit.ArrivalTime != null && visit.WoundCondition != null)
            {
                vs.DepartTime = visit.DepartTime;
                vs.WoundCondition = visit.WoundCondition;
                vs.Notes = visit.Notes;
                vs.Status = "Closed";

                data.CareVisits.Update(vs);
                data.CareVisits.Save();
            }

            //schedule session
            else
            {

            }



            CareID = visit.CareVisitsID;
            TempData["StartStatus"] = "Appointment Started";
            return RedirectToAction("VisitDetails", CareID);
        }


        [HttpPost]
        public IActionResult EndSession(CareVisits visits)
        {

            CareVisits vs = new CareVisits();
            vs = data.CareVisits.Get(visits.CareVisitsID);

            vs.ArrivalTime = visits.ArrivalTime;
            vs.DepartTime = visits.DepartTime;
            vs.WoundCondition = visits.WoundCondition;
            vs.Notes = visits.Notes;
            vs.Status = "Closed";

            data.CareVisits.Update(vs);
            data.CareVisits.Save();


            CareID = visits.CareVisitsID;
            TempData["EndStatus"] = "Appointment Ended";
            return RedirectToAction("VisitDetails", CareID);
        }


        [HttpGet]
        public IActionResult VisitDetails(int ID)
        {
            CareVisits visits = new CareVisits();
            CareContracts contract = new CareContracts();


            if (ID > 0)
            {
                visits = data.CareVisits.Get(ID);
            }
            else
            {
                visits = data.CareVisits.Get(CareID);
            }


            contract = data.CareContracts.Get(visits.ContractNumberID);

            var vw = new CareVisitListViewModel
            {
                CareVisit = data.CareVisits.List(new QueryOptions<CareVisits>
                {

                    Where = b => b.CareVisitsID == visits.CareVisitsID

                }),

                Contracts = data.CareContracts.List(new QueryOptions<CareContracts>
                {
                    Where = a => a.ContractNumberID == visits.ContractNumberID
                }),

                Patients = data.Patients.List(new QueryOptions<Patients>
                {

                    Where = c => c.PatientUserID == contract.PatientUserID

                }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs>
                {

                    Where = d => d.SuburbID == contract.SuburbID

                }),

                Cities = data.Cities.List(new QueryOptions<Cities>
                {

                    Where = e => e.CityID == contract.CityID

                }),






            };


            return View(vw);
        }


        [HttpPost]
        public IActionResult Appointment(CareVisits visit)
        {
            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());

            visit.Status = "Open";
            visit.NurseUserID = ID;

            data.CareVisits.Insert(visit);
            data.CareVisits.Save();

            TempData["CreatedStatus"] = "Appoinment Scheduled Successfully";

            return RedirectToAction("");
        }

        [HttpPost]
        public RedirectToActionResult Filter(string[] filter, bool clear = false)
        {
            // get current route segments from session
            var builder = new CareVisitGridBuilder(HttpContext.Session);

            // clear or update filter route segment values. If update, get author data
            // from database so can add author name slug to author filter value.
            if (clear)
            {
                builder.ClearFilterSegments();
            }
            else
            {
                var Care = data.CareVisits.Get(filter[0].ToInt());
                builder.CurrentRoute.PageNumber = 1;
                builder.LoadFilterSegments(filter, Care);
            }

            // save route data back to session and redirect to Book/List action method,
            // passing dictionary of route segment values to build URL
            builder.SaveRouteSegments();
            return RedirectToAction("List", builder.CurrentRoute);
        }
    }
}

Helping Hands/Areas/Nurse/Controllers/CareVisitController.cs
using Helping_Hands.Data;
using Helping_Hands.Data.GRID;
using Helping_Hands.Data.Repositories;
using Helping_Hands.Models;
using Helping_Hands.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Helping_Hands.Areas.Nurse.Controllers
{

    [Area("Nurse")]
    [Authorize(Roles = "Nurse")]
    public class CareVisitController : Controller
    {
        private HelpingHandsUnitOfWork data { get; set; }
        private GRP0452HelpingHandsDBContext _context { get; set; }

        private static int CareID;

        public CareVisitController(GRP0452HelpingHandsDBContext ctx)
        {
            data = new HelpingHandsUnitOfWork(ctx);
            _context = ctx;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }


        public IActionResult PatientDetails(int id)
        {
            CareContracts contra = new CareContracts();
            Patients patie = new Patients();

            contra = data.CareContracts.Get(id);

            int? ID = contra.PatientUserID;
            patie = data.Patients.Get(Convert.ToInt32(contra.PatientUserID));

            var pt = new PatientViewModels
            {
                Patients = data.Patients.List(new QueryOptions<Patients>
                {
                    Where = a => a.PatientUserID == Convert.ToInt32(contra.PatientUserID)

                }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs>
                {
                    Where = b => b.SuburbID == patie.SuburbID
                }),
                Cities = data.Cities.List(new QueryOptions<Cities>
                {
                    Where = c => c.CityID == patie.CityID
                }),

                ChronicAccoms = data.ChronicAccoms.List(new QueryOptions<ChronicAccoms>
                {
                    Where = d => d.PatientUserID == patie.PatientUserID
                }),

                ChronicInfections = data.ChronicInfections.List(new QueryOptions<ChronicInfections>
                {

                })


            };


            var Patient = data.Patients.Get(Convert.ToInt32(ID));


            return View(pt);
        }


        [HttpGet]
        public IActionResult List(CareVisitGridDTO vals)
        {
            string DefaultSort = nameof(CareVisits.VisitDate);
            var builder = new CareVisitGridBuilder(HttpContext.Session, vals, defaultSortField: nameof(CareVisits.VisitDate));
            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());

            var options = new CareVisitQueryOptions
            {

                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection,
                WhereClauses = new WhereClauses<CareVisits>
                {
                    t =>t.NurseUserID == ID
                }

            };




            options.SortFilter(builder);


            var vw = new CareVisitListViewModel
            {

                CareVisit = data.CareVisits.List(options),

                Patients = data.Patients.List(new QueryOptions<Patients>
                {

                    OrderBy = a => a.FirstName
                }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs> { }),
                Cities = data.Cities.List(new QueryOptions<Cities> { }),
                Contracts = data.CareContracts.List(new QueryOptions<CareContracts> { }),

                CurrentRoute = builder.CurrentRoute,


                TotalPages = builder.GetTotalPages(data.CareVisits.Count)


            };

            ////Substrating time and date

            //DateTime date = DateTime.Today;

            //DateTime fort = date.AddDays(-32);
            //ViewBag.Date = fort.ToString("D"); //|| DateTime.Today.ToString("dd");

            return View(vw);


        }

       
        public IActionResult StartSession(CareVisits visit)
        {
            CareVisits vs = new CareVisits();
            vs = data.CareVisits.Get(visit.CareVisitsID);


            //Start Session
            if (visit.DepartTime == null && visit.WoundCondition == null)
            {

                vs.ArrivalTime = visit.ArrivalTime;

                data.CareVisits.Update(vs);

                data.CareVisits.Save();

                CareID = visit.CareVisitsID;
                TempData["StartStatus"] = "Appointment Started";
                return RedirectToAction("VisitDetails", CareID);
            }

            //End Session
            else if (visit.ArrivalTime != null && visit.WoundCondition != null)
            {
                vs.DepartTime = visit.DepartTime;
                vs.WoundCondition = visit.WoundCondition;
                vs.Notes = visit.Notes;
                vs.Status = "Closed";

                data.CareVisits.Update(vs);
                data.CareVisits.Save();

                CareID = visit.CareVisitsID;
                TempData["StartStatus"] = "Appointment Started";
                return RedirectToAction("VisitDetails", CareID);
            }

            //schedule session
            else
            {

            }



            CareID = visit.CareVisitsID;
            TempData["StartStatus"] = "Appointment Started";
            return RedirectToAction("VisitDetails", CareID);
        }


        
        public IActionResult EndSession(CareVisits visits)
        {

            CareVisits vs = new CareVisits();
            vs = data.CareVisits.Get(visits.CareVisitsID);

            vs.ArrivalTime = visits.ArrivalTime;
            vs.DepartTime = visits.DepartTime;
            vs.WoundCondition = visits.WoundCondition;
            vs.Notes = visits.Notes;
            vs.Status = "Closed";

            data.CareVisits.Update(vs);
            data.CareVisits.Save();


            CareID = visits.CareVisitsID;
            TempData["EndStatus"] = "Appointment Ended";
            return RedirectToAction("VisitDetails", CareID);
        }


        [HttpGet]
        public IActionResult VisitDetails(int ID)
        {
            CareVisits visits = new CareVisits();
            CareContracts contract = new CareContracts();


            if (ID > 0)
            {
                visits = data.CareVisits.Get(ID);
            }
            else
            {
                visits = data.CareVisits.Get(CareID);
            }


            contract = data.CareContracts.Get(visits.ContractNumberID);

            var vw = new CareVisitListViewModel
            {
                CareVisit = data.CareVisits.List(new QueryOptions<CareVisits>
                {

                    Where = b => b.CareVisitsID == visits.CareVisitsID

                }),

                Contracts = data.CareContracts.List(new QueryOptions<CareContracts>
                {
                    Where = a => a.ContractNumberID == visits.ContractNumberID
                }),

                Patients = data.Patients.List(new QueryOptions<Patients>
                {

                    Where = c => c.PatientUserID == contract.PatientUserID

                }),

                Suburbs = data.Suburb.List(new QueryOptions<Suburbs>
                {

                    Where = d => d.SuburbID == contract.SuburbID

                }),

                Cities = data.Cities.List(new QueryOptions<Cities>
                {

                    Where = e => e.CityID == contract.CityID

                }),






            };


            return View(vw);
        }


        [HttpPost]
        public IActionResult Appointment(CareVisits visit)
        {
            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());

            visit.Status = "Open";
            visit.NurseUserID = ID;

            data.CareVisits.Insert(visit);
            data.CareVisits.Save();

            TempData["CreatedStatus"] = "Appoinment Scheduled Successfully";

            return RedirectToAction("");
        }

        [HttpPost]
        public RedirectToActionResult Filter(string[] filter, bool clear = false)
        {
            // get current route segments from session
            var builder = new CareVisitGridBuilder(HttpContext.Session);

            // clear or update filter route segment values. If update, get author data
            // from database so can add author name slug to author filter value.
            if (clear)
            {
                builder.ClearFilterSegments();
            }
            else
            {
                var Care = data.CareVisits.Get(filter[0].ToInt());
                builder.CurrentRoute.PageNumber = 1;
                builder.LoadFilterSegments(filter, Care);
            }

            // save route data back to session and redirect to Book/List action method,
            // passing dictionary of route segment values to build URL
            builder.SaveRouteSegments();
            return RedirectToAction("List", builder.CurrentRoute);
        }
    }
}

Helping Hands/Areas/Manager/Views/CareVisit/List.cshtml
@model CareVisitListViewModel

@{
    ViewData["Title"] = " | Manager ";
    Layout = "_LayoutManager";

    //aliases to make paging and sorting code shorter;
    RouteDictionary current = Model.CurrentRoute;
    RouteDictionary routes = Model.CurrentRoute.Clone();
}






<h2>Care Visits</h2>
<br />
<br />
<div>
    @if (TempData.Keys.Contains("CreatedStatus"))
    {
        <div>
            <h2>

                @TempData["CreatedStatus"]

            </h2>
        </div>
    }
    <br />
</div>
<div class="row">
    <div class="col-9">
        <form asp-action="Filter" method="post" class="form-inline">

            <div class="row">

                <input class="form-control" data-toggle="tooltip" data-placement="top" title="Email Field, e.g YourName@domain.com" placeholder="Search by Patient Name" />
                <button type="submit" class="btn btn-primary mr-2" asp-controller="CareContract" asp-action="Search">Search</button>
            </div>

            <div class="row">
                <div>
                    <label>Status: </label>
                    <select name="filter" class="form-control m-2"
                            asp-items="@(new SelectList(
                        Model.Status, "Key", "Value", current.VisitStatusFilter))">
                        <option value="@CareVisitGridDTO.DefaultFilter">All</option>
                    </select>
                </div>

                <div>
                    <label>Period: </label>
                    <select name="filter" class="form-control m-2"
                            asp-items="@(new SelectList(
                        Model.Period, "Key", "Value", current.PeriodFilter))">
                        <option value="@CareVisitGridDTO.DefaultFilter">All</option>
                    </select>
                </div>

                @*<div>
                    <label>Nurse: </label>
                    <select name="filter" class="form-control m-2"
                            asp-items="@(new SelectList(
                        Model.Nurses, "NurseUserID", "FirstName", current.NurseFilter))">
                        <option value="@CareVisitGridDTO.DefaultFilter">All</option>
                    </select>
                </div>*@

                @*<div>
            <label>Patient: </label>
            <select name="filter" class="form-control m-2"
                    asp-items="@(new SelectList(
                Model.Patients, "PatientUserID", "FirstName", current.PatientFilter))">
                <option value="@CareVisitGridDTO.DefaultFilter">All</option>
            </select>
        </div>*@

                <button type="submit" class="btn btn-primary ml-2">Filter</button>
            </div>



        </form>
    </div>
</div>





<table class="table table-striped table-hover align-content-center">
    <thead>
        <tr>
            <th>Nurse Name</th>
            <th>Patient Name</th>
            <th>
                Visit Date
            </th>
            <th>
               Start Time
            </th>
       
            <th>Depart Time</th>           
         

        </tr>
    </thead>
    <tbody>

       


        @foreach (var care in Model.CareVisit)
        {
            // int num = medication.MedicationIngredients.Where(s => s.MedicationID == medication.MedicationID).Select(v => v.ActiveIngredientID).FirstOrDefault();

            <tr>
                @foreach(Helping_Hands.Nurses nurse in Model.Nurses)
                {
                    if(care.NurseUserID == nurse.NurseUserID)
                    {
                        <td>@nurse.FirstName @nurse.Surname</td>
                    }
                }


                @foreach(Helping_Hands.CareContracts pat in Model.Contracts)
                {
                    if(care.ContractNumberID == pat.ContractNumberID)
                    {
                        foreach(Patients pati in Model.Patients)
                        {
                            if(pat.PatientUserID == pati.PatientUserID)
                            {
                                <td>@pati.FirstName @pati.Surname</td>
                            }
                        }
                    }
                }

            <td>@Convert.ToDateTime(care.VisitDate).ToString("MM / dd / yyyy") </td>
                <td>@care.ArrivalTime</td>
               
                 <td>@care.DepartTime</td>                      
             

                <td>
                    <a asp-controller="CareVisit" asp-action="VisitDetails"
                       asp-route-id="@care.CareVisitsID">Details</a>

                <td>
            </tr>
        }
    </tbody>
    </tbody>

</table>

@{
    routes = Model.CurrentRoute.Clone(); // Reset to current route values *@
    for (int i = 1; i <= Model.TotalPages; i++)
    {
        routes.PageNumber = i;
        <a asp-action="List" asp-all-route-data="@routes"
           class="btn btn-primary @Nav.Active(i, current.PageNumber)">@i</a>
    }
}

Helping Hands/Areas/Manager/Views/CareVisit/NurseDetails.cshtml
@model NursesListViewModel

<title>Patient Details</title>

<div class="Details">

    <section>
        @foreach (Helping_Hands.Nurses pp in Model.Nurses)
        {
            <h1>@pp.FirstName @pp.Surname</h1>
        }


    </section>
    <div class="Body">
        <div class="BodyDetails">

            @foreach (Helping_Hands.Nurses pati in Model.Nurses)
            {
                <div class="About Nurse">
                    <h3>Bio</h3>
                    <br />
                    <div class="GenderPart">
                        <label>Gender</label>
                        <span>@pati.Gender</span>
                    </div>

                    <div class="DOBPart">
                        <label>ID Number</label>
                        <span>@pati.IdNumber</span>
                    </div>
                </div>

                <br />

                <div class="ContactInfor">
                    <h3>Contact Information</h3>
                    <br />
                    <div class="ContactPart">
                        <label>Contact Number</label>
                        <span>@pati.NurseContact</span>
                    </div>

                    <div class="EmailPart">
                        <label>Patient Email</label>
                        <span>@pati.EmailAddress</span>
                    </div>

                 

                    @foreach (Helping_Hands.Suburbs sub in Model.Suburbs)
                    {
                        <div class="SuburbPart">
                            <label>Suburb</label>
                            <span>@sub.Name</span>
                        </div>


                    }

                    @foreach (Helping_Hands.Cities cit in Model.Cities)
                    {
                        <div class="CityPart">
                            <label>City</label>
                            <span>@cit.Name</span>
                        </div>
                    }



                </div>
            }

            <div class="SuburbsPart">
                <h3>Prefered Suburbs</h3>
                <br />
                <div class="Subrbs-Part">
                   
                    @foreach (Helping_Hands.PreferedSuburbs accom in Model.PreferedSuburbs)
                    {


                        foreach (Helping_Hands.Suburbs infections in Model.Suburbs)
                        {
                            if (accom.SuburbID == infections.SuburbID)
                            {

                                <span>@infections.Name</span>
                                <span>@infections.PostalCode</span>


                            }
                        }
                    }
                </div>
            </div>

          

        </div>
    </div>

    <button onclick="history.go(-1)">Back</button>
</div>