Helping Hands/Models/ViewModels/ConditionsViewModels.cs
using Helping_Hands.Data;
using System.Collections.Generic;

namespace Helping_Hands.Models.ViewModels
{
    public class ConditionsViewModels
    {
        public IEnumerable<ChronicAccoms> ChronicAccoms { get; set; }
        public IEnumerable<ChronicInfections> ChronicInfections { get; set; }
        public IEnumerable<Patients> Patients { get; set; }



        public RouteDictionary CurrentRoute { get; set; }
        public int TotalPages { get; set; }

        public int[] PageSizes => new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    }
}

Helping Hands/Areas/Manager/Controllers/ConditionsController.cs
using Helping_Hands.Data.GRID;
using Helping_Hands.Data.Repositories;
using Helping_Hands.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Helping_Hands.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = "Manager")]
    public class ConditionsController : Controller
    {
        private HelpingHandsUnitOfWork data { get; set; }
        public ConditionsController(GRP0452HelpingHandsDBContext ctx) => data = new HelpingHandsUnitOfWork(ctx);


        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult List(ConditionsGridDTO vals)
        {
            // get GridBuilder object, load route segment values, store in session
            string defaultSort = nameof(ChronicInfections.ConditionName);
            var builder = new ConditionsGridBuilder(HttpContext.Session, vals, defaultSortField: nameof(ChronicInfections.ConditionName));
            // builder.SaveRouteSegments();

            // create options for querying authors
            var options = new ConditionsQueryOptions
            {
                //Includes = "BookAuthors.Book",

                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection,
                Where = a => a.Status == "Active"
            };

            // options.SortFilter(builder); uncheck if errors are encountered sorting
            options.SortFilter(builder);
            // OrderBy depends on value of SortField route
            //if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
            //    options.OrderBy = a => a.FirstName;

            //else
            //    options.OrderBy = a => a.Surname;

            var vm = new ConditionsViewModels
            {
                ChronicInfections = data.ChronicInfections.List(options),

                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.ChronicInfections.Count)
            };


            return View(vm);

        }


        [HttpPost]
        public IActionResult Add(ChronicInfections pref)
        {

            try
            {
                pref.Status = "Active";
                data.ChronicInfections.Insert(pref);
                data.Save();

                TempData["ConditionStatus"] = "Something went wrong";
            }
            catch
            {
                TempData["ConditionStatus"] = "Something went wrong";
                return RedirectToAction("List");
            }


            return RedirectToAction("List");
        }

        public IActionResult Delete(int id)
        {
            try
            {
                ChronicInfections city = new ChronicInfections();
                city = data.ChronicInfections.Get(id);
                city.Status = "InActive";

                data.ChronicInfections.Update(city);
                data.ChronicInfections.Save();

                TempData["ConditionStatus"] = " Succesfully Deleted";

            }
            catch
            {
                TempData["ConditionStatus"] = "Something went wrong";
                return RedirectToAction("List");
            }


            return RedirectToAction("List");
        }

    }
}

Helping Hands/Areas/Patient/Controllers/ConditionsController.cs
using Helping_Hands.Data.GRID;
using Helping_Hands.Data.Repositories;
using Helping_Hands.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Helping_Hands.Areas.Patient.Controllers
{

    [Authorize(Roles = "Patient")]
    [Area("Patient")]
    public class ConditionsController : Controller
    {
        private HelpingHandsUnitOfWork data { get; set; }
        public ConditionsController(GRP0452HelpingHandsDBContext ctx) => data = new HelpingHandsUnitOfWork(ctx);

        private static int ContraID { get; set; }

        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult List(ConditionsGridDTO vals)
        {

            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());

            // get GridBuilder object, load route segment values, store in session
            string defaultSort = nameof(ChronicInfections.ConditionName);
            var builder = new ConditionsGridBuilder(HttpContext.Session, vals, defaultSortField: nameof(ChronicInfections.ConditionName));
            // builder.SaveRouteSegments();

            // create options for querying authors
            var options = new ConditionsQueryOptions
            {
                //Includes = "BookAuthors.Book",

                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection,
                Where = a => a.Status == "Active"
            };

            // options.SortFilter(builder); uncheck if errors are encountered sorting
            options.SortFilter(builder);
            // OrderBy depends on value of SortField route
            //if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
            //    options.OrderBy = a => a.FirstName;

            //else
            //    options.OrderBy = a => a.Surname;

            var vm = new ConditionsViewModels
            {
                ChronicInfections = data.ChronicInfections.List(options),
                ChronicAccoms = data.ChronicAccoms.List(new QueryOptions<ChronicAccoms>
                {
                    Where = a => a.PatientUserID == ID && a.Status == "Active"
                }),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.ChronicInfections.Count)
            };


            return View(vm);

        }


        [HttpPost]
        public IActionResult Add(ChronicAccoms pref)
        {
            int ID = Convert.ToInt32(TempData.Peek("UserID").ToString());
            try
            {

                pref.Status = "Active";
                pref.PatientUserID = ID;
                data.ChronicAccoms.Insert(pref);
                data.Save();

                TempData["ConditionStatus"] = "Something went wrong";
            }
            catch
            {
                TempData["ConditionStatus"] = "Something went wrong";
                return RedirectToAction("List");
            }


            return RedirectToAction("List");
        }

        public IActionResult Delete(int id)
        {
            try
            {
                ChronicAccoms coms = new ChronicAccoms();
                coms = data.ChronicAccoms.Get(id);
                coms.Status = "InActive";

                data.ChronicAccoms.Update(coms);
                data.ChronicAccoms.Save();

                TempData["ConditionStatus"] = " Succesfully Deleted";

            }
            catch
            {
                TempData["ConditionStatus"] = "Something went wrong";
                return RedirectToAction("List");
            }


            return RedirectToAction("List");
        }

    }
}

Helping Hands/Areas/Patient/Views/Conditions/List.cshtml
@model ConditionsViewModels

@{
    ViewData["Title"] = " | Medical Conditions ";
    Layout = "_Layout_Patient";

    //aliases to make paging and sorting code shorter;
    RouteDictionary current = Model.CurrentRoute;
    RouteDictionary routes = Model.CurrentRoute.Clone();
}

<head>

    <link rel="stylesheet" href=~/css/style.css />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>

<hr />
<br />



<h2>Chronic Conditions </h2>
<br />



<br />

<div>
    @{


        if (TempData.Keys.Contains("ConditionStatus"))
        {
            <div>
                <h2>
                    @TempData["ConditionStatus"]

                </h2>
            </div>
        }

    }

</div>

<br />
<div class="row">
    <div class="col-9">

        <div>
            <button data-dismiss="modal" data-toggle="modal" data-target="#AddCondition" class="btn btn-primary">Add Chronic Condition</button>
        </div>
    </div>
</div>


<table class="table table-striped table-hover align-content-center">
    <thead>
        <tr>

            <th>
                Name
            </th>
            <th>Description</th>
           

        </tr>
    </thead>
    <tbody>
        @foreach (Helping_Hands.ChronicInfections infections in Model.ChronicInfections)
        {
            // int num = medication.MedicationIngredients.Where(s => s.MedicationID == medication.MedicationID).Select(v => v.ActiveIngredientID).FirstOrDefault();


            foreach (Helping_Hands.ChronicAccoms accoms in Model.ChronicAccoms)
            {
                if (accoms.ChronicID == infections.ChronicID)
                {
                    ViewBag.Chronic = accoms.ChronicAccomID;

                    <tr>


                        <td>@infections.ConditionName</td>
                        <td>@infections.Description</td>
                        <td>
                            <a data-dismiss="modal" data-toggle="modal" data-target="#ConfirmationDeleteCity" class="btn btn-primary">Remove</a>
                            <a data-dismiss="modal" data-toggle="modal" data-target="#ConfirmationUpdateCity" class="btn btn-primary">Update</a>
                        </td>

                    </tr>
                }

            }

        }


    </tbody>

</table>

@*Modal Pop up to Confirm Add *@
<div class="modal fade" id="ConfirmationDeleteCity" tabindex="-2" role="dialog" aria-labelledby="ConfirmationAcceptance" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                
                <div>
                    <span>
                        Chronic condition will be deleted from your profile. Are you sure?
                    </span>
                </div>

                @*<input type="hidden"  asp-for="@Prefsub.SuburbID" hidden="hidden" />*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a type="button" class="btn btn-primary" asp-controller="Conditions" asp-route-id="@ViewBag.Chronic" asp-action="Delete">Yes</a>
            </div>
        </div>
    </div>
</div>

<form method="post" asp-action="Add">

    @foreach (Helping_Hands.ChronicAccoms pref in Model.ChronicAccoms)
    {
        
        //Modal Pop up for Adding Condition
        <div class="modal fade" id="AddCondition" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Chronic Condition</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <label>Conditions</label>
                        <select asp-for="@pref.ChronicID" class="form-control">
                            <option value="">Select Condition</option>
                            
                                @foreach(Helping_Hands.ChronicInfections cond in Model.ChronicInfections)
                                  {
                                       <option value="@cond.ChronicID">
                                           @cond.ConditionName
                                       </option>
                                  }
                           
                        </select>

                        <br />


                        

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button data-dismiss="modal" data-toggle="modal" data-target="#ConfirmationAddCondition" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>



        @*Modal Pop up to Confirm Add *@
        <div class="modal fade" id="ConfirmationAddCondition" tabindex="-2" role="dialog" aria-labelledby="ConfirmationAcceptance" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <div class="CreateRecord">
                            <span>
                                Do you want to add Chronic Condition to your profile?
                            </span>
                        </div>

                        <input hidden="hidden" type="text" placeholder="Condition Name" asp-for="@pref.ChronicID" class="form-control" />
                        @*<input hidden="hidden" type="text" placeholder="Description" class="form-control" asp-for="@pref.ChronicAccomID" />*@
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" asp-action="Add">Yes</button>
                    </div>
                </div>
            </div>
        </div>

    }


</form>









@{
    routes = Model.CurrentRoute.Clone(); // Reset to current route values *@
    for (int i = 1; i <= Model.TotalPages; i++)
    {
        routes.PageNumber = i;
        <a asp-action="List" asp-all-route-data="@routes"
           class="btn btn-primary @Nav.Active(i, current.PageNumber)">@i</a>
    }
}